### ISSUE TITLE
ParseError when installing helpdesk

### ISSUE THREAD

**Issue by yastri** [mustafirus/odoo_addons#5]
Hi, 
I try to install this module, and there's error as below 

```
helpdesk_lite/models/helpdesk_team.py", line 50, in get_alias_values
    defaults = safe_eval(self.alias_defaults or "{}")
odoo.tools.convert.ParseError: "'module' object is not callable" while parsing /opt/addons-custom/helpdesk_lite/views/helpdesk_data.xml:22, near
<record model="helpdesk_lite.team" id="team_alpha">
            <field name="name">Alpha Team</field>
        </record>
```

**Comment by mustafirus** [comment]
i cant reproduce error
can you give more info?

**Comment by KareemAbuzaid** [comment]
Hello @mustafirus 

I am facing the same issue. I did some checking. And below are my findings:
- The error is caused by line 68 in the `helpdesk_team.py` file.
- It seems that there is a problem importing `safe_eval`.
- If you take a look at the `__init__.py` file located in `/odoo/tools/`, you will see that `safe_eval` is not imported.
- For this reason the proper way of importing `safe_eval` would be:
`from odoo.tools.safe_eval import safe_eval`

Based on the above I will open a merge request to update the source code.

Brgds
Kareem
